sudo: required
language: c
services:
- docker-ce
script:
- docker build --rm -t nobonobo/broadway-alpine .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push nobonobo/broadway-alpine;
    fi
